# Generated by Django 3.0.3 on 2020-02-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLista', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTare', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fkLista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello1.Lista')),
            ],
        ),
        migrations.AddField(
            model_name='lista',
            name='fkTablero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello1.Tablero'),
        ),
    ]
